- hosts: aws
  gather_facts: yes
  tasks:
  - name: Create second
    command: openssl req -nodes -x509 -days 365 -subj "/C=US/ST=CA/L=San Jose/O=rakesh/CN=balusa" -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt

